# system-wide aliases
alias btop='sudo btop'

# system-wide customizations
if [[ "$-" != *i* ]]; then
    return
fi
eval "$(starship init bash)"
if [[ -n "$SSH_TTY" ]]; then
    clear
    fastfetch
fi
